kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app-test-pvc
  namespace: default
  labels:
    app: app-test
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
