apiVersion: v1
kind: Service
metadata:
  name: flask-app-clusterip
  namespace: test
  labels:
    appname: flask-app-service
    component: frontend
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    appname: flask-pod
    component: frontend